/**
 * About automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AboutApps} from "./AboutApps";
import {AboutLink} from "./AboutLink";
export interface About {
    apiVersion?: string
    title?: string
    description?: string
    termsOfService?: string
    contactName?: string
    contactUrl?: string
    contactEmail?: string
    licenseName?: string
    licenseUrl?: string
    paymentCurrency?: string
    categories?: Array<string>
    scopes?: Array<string>
    apps?: AboutApps
    links?: Array<AboutLink>
}
