/**
 * AppModelIssueCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {IssueCollection} from "./IssueCollection";
export type AppModelIssueCollection = IssueCollection;
