/**
 * AppModelPullRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {PullRequest} from "./PullRequest";
export type AppModelPullRequest = PullRequest;
