/**
 * AppModelCommentCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommentCollection} from "./CommentCollection";
export type AppModelCommentCollection = CommentCollection;
