/**
 * AppModelDocumentExportRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {DocumentExportRequest} from "./DocumentExportRequest";
export type AppModelDocumentExportRequest = DocumentExportRequest;
