/**
 * AppModelDocumentPreview automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {DocumentPreview} from "./DocumentPreview";
export type AppModelDocumentPreview = DocumentPreview;
