/**
 * AppModelDocumentCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {DocumentCollection} from "./DocumentCollection";
export type AppModelDocumentCollection = DocumentCollection;
