/**
 * AppModelTagChangelog automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagChangelog} from "./TagChangelog";
export type AppModelTagChangelog = TagChangelog;
