/**
 * AppModelVersionQuery automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {VersionQuery} from "./VersionQuery";
export type AppModelVersionQuery = VersionQuery;
