/**
 * AppModelTagCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagCollection} from "./TagCollection";
export type AppModelTagCollection = TagCollection;
