/**
 * AppModelIssueCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {IssueCreate} from "./IssueCreate";
export type AppModelIssueCreate = IssueCreate;
