/**
 * AppModelPullRequestCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {PullRequestCollection} from "./PullRequestCollection";
export type AppModelPullRequestCollection = PullRequestCollection;
