/**
 * AppModelCollectionQuery automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CollectionQuery} from "./CollectionQuery";
export type AppModelCollectionQuery = CollectionQuery;
