/**
 * AppModelCommentCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommentCreate} from "./CommentCreate";
export type AppModelCommentCreate = CommentCreate;
