/**
 * AppModelMessage automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Message} from "./Message";
export type AppModelMessage = Message;
