/**
 * AppModelDocumentCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {DocumentCreate} from "./DocumentCreate";
export type AppModelDocumentCreate = DocumentCreate;
