/**
 * AppModelPullRequestCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {PullRequestCreate} from "./PullRequestCreate";
export type AppModelPullRequestCreate = PullRequestCreate;
