/**
 * ArgumentDistribution automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ArgumentDistribution {
    total?: number
    path?: number
    query?: number
    header?: number
}

