/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import axios, {AxiosRequestConfig} from "axios";
import {ClientAbstract, TokenStoreInterface} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {StarTag} from "./StarTag";
import {TagTag} from "./TagTag";
import {PullRequestTag} from "./PullRequestTag";
import {IssueTag} from "./IssueTag";
import {DocumentTag} from "./DocumentTag";
import {DefaultTag} from "./DefaultTag";
import {ExploreTag} from "./ExploreTag";

export class Client extends ClientAbstract {
    public star(): StarTag
    {
        return new StarTag(
            this.httpClient,
            this.parser
        );
    }

    public tag(): TagTag
    {
        return new TagTag(
            this.httpClient,
            this.parser
        );
    }

    public pullRequest(): PullRequestTag
    {
        return new PullRequestTag(
            this.httpClient,
            this.parser
        );
    }

    public issue(): IssueTag
    {
        return new IssueTag(
            this.httpClient,
            this.parser
        );
    }

    public document(): DocumentTag
    {
        return new DocumentTag(
            this.httpClient,
            this.parser
        );
    }

    public default(): DefaultTag
    {
        return new DefaultTag(
            this.httpClient,
            this.parser
        );
    }

    public explore(): ExploreTag
    {
        return new ExploreTag(
            this.httpClient,
            this.parser
        );
    }



}
