/**
 * CommitCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Commit} from "./Commit";
export type CommitCollection = Collection<Commit>;
