/**
 * CommentCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Comment} from "./Comment";

export interface CommentCreate extends Comment {
}

