/**
 * CommentCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {Comment} from "./Comment";

export interface CommentCollection extends Collection<Comment> {
}

