/**
 * CommentReactions automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface CommentReactions {
    like?: number
    dislike?: number
    laugh?: number
    hooray?: number
    confused?: number
    heart?: number
    rocket?: number
    eyes?: number
}

