/**
 * CommitPrevious automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface CommitPrevious {
    id?: number
    message?: string
    commitHash?: string
    spec?: any
    insertDate?: string
}
