/**
 * Commit automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Document} from "./Document";
import {User} from "./User";
import {CommitPrevious} from "./CommitPrevious";
export interface Commit {
    id?: number
    document?: Document
    user?: User
    previous?: CommitPrevious
    message?: string
    commitHash?: string
    spec?: any
    insertDate?: string
}
