/**
 * DocumentCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {Document} from "./Document";

export interface DocumentCollection extends Collection<Document> {
}

