/**
 * DocumentUserDocumentIssueIdPath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentUserDocumentIssueIdPath {
    user?: string
    document?: string
    id?: string
}
