/**
 * DocumentPreview automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Repository} from "./Repository";
import {Tag} from "./Tag";
export interface DocumentPreview {
    repositories?: Array<Repository>
    tags?: Array<Tag>
    types?: Array<string>
}
