/**
 * DocumentByUserAndDocumentPullRequestAndIdResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {PullRequest} from "./PullRequest";
import {Passthru} from "./Passthru";
import {Message} from "./Message";

export default class DocumentByUserAndDocumentPullRequestAndIdResource extends ResourceAbstract {
    private url: string;

    private user: string;
    private document: string;
    private id: string;

    public constructor(user: string, document: string, id: string, baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);

        this.user = user;
        this.document = document;
        this.id = id;

        this.url = baseUrl + "/document/"+user+"/"+document+"/pull_request/"+id+"";
    }

    /**
     * Returns a pull request
     *
     * @returns {Promise<AxiosResponse<PullRequest>>}
     */
    public async getDocumentUserDocumentPullRequestId(): Promise<AxiosResponse<PullRequest>> {
        let params: AxiosRequestConfig = {
            method: 'GET',
        };

        return this.httpClient.get<PullRequest>(this.url, params);
    }

    /**
     * Merges a pull request
     *
     * @param {Passthru} data
     * @returns {Promise<AxiosResponse<Message>>}
     */
    public async putDocumentUserDocumentPullRequestId(data: Passthru): Promise<AxiosResponse<Message>> {
        let params: AxiosRequestConfig = {
            method: 'PUT',
        };

        return this.httpClient.put<Message>(this.url, data, params);
    }

    /**
     * Closes a pull request
     *
     * @returns {Promise<AxiosResponse<Message>>}
     */
    public async deleteDocumentUserDocumentPullRequestId(): Promise<AxiosResponse<Message>> {
        let params: AxiosRequestConfig = {
            method: 'DELETE',
        };

        return this.httpClient.delete(this.url, params);
    }

}
