/**
 * DocumentPreviewTypes automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentPreviewTypes {
    api?: Array<string>
    schema?: Array<string>
}
