/**
 * DocumentByUserAndDocumentChangelogResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {Passthru} from "./Passthru";
import {TagChangelog} from "./TagChangelog";

export default class DocumentByUserAndDocumentChangelogResource extends ResourceAbstract {
    private url: string;

    private user: string;
    private document: string;

    public constructor(user: string, document: string, baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);

        this.user = user;
        this.document = document;

        this.url = baseUrl + "/document/"+user+"/"+document+"/changelog";
    }

    /**
     * Generates the changelog for the current release
     *
     * @param {Passthru} data
     * @returns {Promise<AxiosResponse<TagChangelog>>}
     */
    public async postDocumentUserDocumentChangelog(data: Passthru): Promise<AxiosResponse<TagChangelog>> {
        let params: AxiosRequestConfig = {
            method: 'POST',
        };

        return this.httpClient.post<TagChangelog>(this.url, data, params);
    }

}
