/**
 * DocumentByUserAndDocumentExportResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {DocumentExportRequest} from "./DocumentExportRequest";
import {DocumentExportResponse} from "./DocumentExportResponse";

export default class DocumentByUserAndDocumentExportResource extends ResourceAbstract {
    private url: string;

    private user: string;
    private document: string;

    public constructor(user: string, document: string, baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);

        this.user = user;
        this.document = document;

        this.url = baseUrl + "/document/"+user+"/"+document+"/export";
    }

    /**
     * Export this document
     *
     * @param {DocumentExportRequest} data
     * @returns {Promise<AxiosResponse<DocumentExportResponse>>}
     */
    public async postDocumentUserDocumentExport(data: DocumentExportRequest): Promise<AxiosResponse<DocumentExportResponse>> {
        let params: AxiosRequestConfig = {
            method: 'POST',
        };

        return this.httpClient.post<DocumentExportResponse>(this.url, data, params);
    }

}
