/**
 * DocumentUserDocumentIssueIdCommentPath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentUserDocumentIssueIdCommentPath {
    user?: string
    document?: string
    id?: string
}
