/**
 * DocumentUserDocumentPreviewPath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentUserDocumentPreviewPath {
    user?: string
    document?: string
}
