/**
 * DocumentCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentCreate {
    name: string
    description?: string
    private?: boolean
    baseVersion?: string
    homepage?: string
}
