/**
 * DocumentUserDocumentPullRequestIdPath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentUserDocumentPullRequestIdPath {
    user?: string
    document?: string
    id?: string
}
