/**
 * DocumentByUserAndDocumentForkResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {Passthru} from "./Passthru";
import {Message} from "./Message";

export default class DocumentByUserAndDocumentForkResource extends ResourceAbstract {
    private url: string;

    private user: string;
    private document: string;

    public constructor(user: string, document: string, baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);

        this.user = user;
        this.document = document;

        this.url = baseUrl + "/document/"+user+"/"+document+"/fork";
    }

    /**
     * Fork this document
     *
     * @param {Passthru} data
     * @returns {Promise<AxiosResponse<Message>>}
     */
    public async postDocumentUserDocumentFork(data: Passthru): Promise<AxiosResponse<Message>> {
        let params: AxiosRequestConfig = {
            method: 'POST',
        };

        return this.httpClient.post<Message>(this.url, data, params);
    }

}
