/**
 * DocumentUserDocumentStarPath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentUserDocumentStarPath {
    user?: string
    document?: string
}
