/**
 * DocumentByUserAndDocumentTagResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {AppModelCollectionQuery} from "./AppModelCollectionQuery";
import {TagCollection} from "./TagCollection";
import {Passthru} from "./Passthru";
import {Message} from "./Message";

export default class DocumentByUserAndDocumentTagResource extends ResourceAbstract {
    private url: string;

    private user: string;
    private document: string;

    public constructor(user: string, document: string, baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);

        this.user = user;
        this.document = document;

        this.url = baseUrl + "/document/"+user+"/"+document+"/tag";
    }

    /**
     * Returns all tags for a document
     *
     * @param {AppModelCollectionQuery} query
     * @returns {Promise<AxiosResponse<TagCollection>>}
     */
    public async getDocumentUserDocumentTag(query?: AppModelCollectionQuery): Promise<AxiosResponse<TagCollection>> {
        let params: AxiosRequestConfig = {
            method: 'GET',
            params: query,
        };

        return this.httpClient.get<TagCollection>(this.url, params);
    }

    /**
     * Creates a new tag
     *
     * @param {Passthru} data
     * @returns {Promise<AxiosResponse<Message>>}
     */
    public async postDocumentUserDocumentTag(data: Passthru): Promise<AxiosResponse<Message>> {
        let params: AxiosRequestConfig = {
            method: 'POST',
        };

        return this.httpClient.post<Message>(this.url, data, params);
    }

}
