/**
 * DocumentTag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TagAbstract, HttpRequest} from "sdkgen-client"
import {ClientException, UnknownStatusCodeException} from "sdkgen-client";

import {Document} from "./Document";
import {DocumentCollection} from "./DocumentCollection";
import {DocumentCreate} from "./DocumentCreate";
import {DocumentExportRequest} from "./DocumentExportRequest";
import {DocumentExportResponse} from "./DocumentExportResponse";
import {DocumentMeta} from "./DocumentMeta";
import {DocumentPreview} from "./DocumentPreview";
import {DocumentUpdate} from "./DocumentUpdate";
import {Message} from "./Message";
import {MessageException} from "./MessageException";
import {Passthru} from "./Passthru";

export class DocumentTag extends TagAbstract {
    /**
     * Reverts your document to this commit
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async revert(user: string, document: string, id: string, payload: Passthru): Promise<Message> {
        const url = this.parser.url('/document/:user/:document/revert/:id', {
            'user': user,
            'document': document,
            'id': id,
        });

        let request: HttpRequest = {
            url: url,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Resets your document to the latest source
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async reset(user: string, document: string, payload: Passthru): Promise<Message> {
        const url = this.parser.url('/document/:user/:document/reset', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Fork this document
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async fork(user: string, document: string): Promise<Message> {
        const url = this.parser.url('/document/:user/:document/fork', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Import a TypeAPI specification to this document
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async import(user: string, document: string, payload: Passthru): Promise<Message> {
        const url = this.parser.url('/document/:user/:document/import', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Export this document
     *
     * @returns {Promise<DocumentExportResponse>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async export(user: string, document: string, payload: DocumentExportRequest): Promise<DocumentExportResponse> {
        const url = this.parser.url('/document/:user/:document/export', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as DocumentExportResponse;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Stars this document
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async star(user: string, document: string, payload: Passthru): Promise<Message> {
        const url = this.parser.url('/document/:user/:document/star', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Removes a document
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async delete(user: string, document: string): Promise<Message> {
        const url = this.parser.url('/document/:user/:document', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'DELETE',
            headers: {
            },
            params: this.parser.query({
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Updates the meta data of an document
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async meta(user: string, document: string, payload: DocumentMeta): Promise<Message> {
        const url = this.parser.url('/document/:user/:document/meta', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Updates a document
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async update(user: string, document: string, payload: DocumentUpdate): Promise<Message> {
        const url = this.parser.url('/document/:user/:document', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Creates a new document
     *
     * @returns {Promise<Message>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async create(user: string, payload: DocumentCreate): Promise<Message> {
        const url = this.parser.url('/document/:user', {
            'user': user,
        });

        let request: HttpRequest = {
            url: url,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            params: this.parser.query({
            }, [
            ]),
            data: payload
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Message;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Returns a document preview
     *
     * @returns {Promise<DocumentPreview>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async showPreview(user: string, document: string, version?: string): Promise<DocumentPreview> {
        const url = this.parser.url('/document/:user/:document/preview', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'version': version,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as DocumentPreview;
        }

        const statusCode = response.status;
        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Returns a document
     *
     * @returns {Promise<Document>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async get(user: string, document: string, version?: string): Promise<Document> {
        const url = this.parser.url('/document/:user/:document', {
            'user': user,
            'document': document,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'version': version,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as Document;
        }

        const statusCode = response.status;
        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }
    /**
     * Returns all documents
     *
     * @returns {Promise<DocumentCollection>}
     * @throws {MessageException}
     * @throws {ClientException}
     */
    public async getAll(user: string, startIndex?: number, count?: number, search?: string): Promise<DocumentCollection> {
        const url = this.parser.url('/document/:user', {
            'user': user,
        });

        let request: HttpRequest = {
            url: url,
            method: 'GET',
            headers: {
            },
            params: this.parser.query({
                'startIndex': startIndex,
                'count': count,
                'search': search,
            }, [
            ]),
        };

        const response = await this.httpClient.request(request);
        if (response.ok) {
            return await response.json() as DocumentCollection;
        }

        const statusCode = response.status;
        if (statusCode === 400) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 404) {
            throw new MessageException(await response.json() as Message);
        }

        if (statusCode === 500) {
            throw new MessageException(await response.json() as Message);
        }

        throw new UnknownStatusCodeException('The server returned an unknown status code: ' + statusCode);
    }



}
