/**
 * DocumentByUserAndDocumentPullRequestAndIdCommentResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {AppModelCollectionQuery} from "./AppModelCollectionQuery";
import {CommentCollection} from "./CommentCollection";
import {CommentCreate} from "./CommentCreate";
import {Message} from "./Message";

export default class DocumentByUserAndDocumentPullRequestAndIdCommentResource extends ResourceAbstract {
    private url: string;

    private user: string;
    private document: string;
    private id: string;

    public constructor(user: string, document: string, id: string, baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);

        this.user = user;
        this.document = document;
        this.id = id;

        this.url = baseUrl + "/document/"+user+"/"+document+"/pull_request/"+id+"/comment";
    }

    /**
     * Shows all pull request comments
     *
     * @param {AppModelCollectionQuery} query
     * @returns {Promise<AxiosResponse<CommentCollection>>}
     */
    public async getDocumentUserDocumentPullRequestIdComment(query?: AppModelCollectionQuery): Promise<AxiosResponse<CommentCollection>> {
        let params: AxiosRequestConfig = {
            method: 'GET',
            params: query,
        };

        return this.httpClient.get<CommentCollection>(this.url, params);
    }

    /**
     * Creates a new comment for a pull request
     *
     * @param {CommentCreate} data
     * @returns {Promise<AxiosResponse<Message>>}
     */
    public async postDocumentUserDocumentPullRequestIdComment(data: CommentCreate): Promise<AxiosResponse<Message>> {
        let params: AxiosRequestConfig = {
            method: 'POST',
        };

        return this.httpClient.post<Message>(this.url, data, params);
    }

}
