/**
 * DocumentMeta automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentMeta {
    description?: string
    private?: boolean
    baseVersion?: string
    developmentMode?: boolean
    homepage?: string
}
