/**
 * DocumentExportRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentExportRequest {
    user?: string
    document?: string
    version?: string
    format?: string
}
