/**
 * DocumentByUserAndDocumentIssueResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {AppModelCollectionQuery} from "./AppModelCollectionQuery";
import {IssueCollection} from "./IssueCollection";
import {IssueCreate} from "./IssueCreate";
import {Message} from "./Message";

export default class DocumentByUserAndDocumentIssueResource extends ResourceAbstract {
    private url: string;

    private user: string;
    private document: string;

    public constructor(user: string, document: string, baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);

        this.user = user;
        this.document = document;

        this.url = baseUrl + "/document/"+user+"/"+document+"/issue";
    }

    /**
     * Returns all issues
     *
     * @param {AppModelCollectionQuery} query
     * @returns {Promise<AxiosResponse<IssueCollection>>}
     */
    public async getDocumentUserDocumentIssue(query?: AppModelCollectionQuery): Promise<AxiosResponse<IssueCollection>> {
        let params: AxiosRequestConfig = {
            method: 'GET',
            params: query,
        };

        return this.httpClient.get<IssueCollection>(this.url, params);
    }

    /**
     * Creates a new issue
     *
     * @param {IssueCreate} data
     * @returns {Promise<AxiosResponse<Message>>}
     */
    public async postDocumentUserDocumentIssue(data: IssueCreate): Promise<AxiosResponse<Message>> {
        let params: AxiosRequestConfig = {
            method: 'POST',
        };

        return this.httpClient.post<Message>(this.url, data, params);
    }

}
