/**
 * DocumentByUserResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {AppModelCollectionQuery} from "./AppModelCollectionQuery";
import {DocumentCollection} from "./DocumentCollection";
import {DocumentCreate} from "./DocumentCreate";
import {Message} from "./Message";

export default class DocumentByUserResource extends ResourceAbstract {
    private url: string;

    private user: string;

    public constructor(user: string, baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);

        this.user = user;

        this.url = baseUrl + "/document/"+user+"";
    }

    /**
     * Returns all documents
     *
     * @param {AppModelCollectionQuery} query
     * @returns {Promise<AxiosResponse<DocumentCollection>>}
     */
    public async getDocumentUser(query?: AppModelCollectionQuery): Promise<AxiosResponse<DocumentCollection>> {
        let params: AxiosRequestConfig = {
            method: 'GET',
            params: query,
        };

        return this.httpClient.get<DocumentCollection>(this.url, params);
    }

    /**
     * Creates a new document
     *
     * @param {DocumentCreate} data
     * @returns {Promise<AxiosResponse<Message>>}
     */
    public async postDocumentUser(data: DocumentCreate): Promise<AxiosResponse<Message>> {
        let params: AxiosRequestConfig = {
            method: 'POST',
        };

        return this.httpClient.post<Message>(this.url, data, params);
    }

}
