/**
 * DocumentPreview automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Tag} from "./Tag";
import {DocumentRepository} from "./DocumentRepository";

export interface DocumentPreview {
    tags?: Array<Tag>
    repositories?: Array<DocumentRepository>
    types?: Array<string>
}

