/**
 * DocumentCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Document} from "./Document";
export interface DocumentCreate extends Document {
}
