/**
 * DocumentUserDocumentExportPath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentUserDocumentExportPath {
    user?: string
    document?: string
}
