/**
 * DocumentUserDocumentTagIdPath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentUserDocumentTagIdPath {
    user?: string
    document?: string
    id?: string
}
