/**
 * DocumentMeta automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentMeta {
    description?: string
    baseUrl?: string
    baseVersion?: string
    keywords?: string
    homepage?: string
    license?: string
}
