/**
 * DocumentUserDocumentPullRequestPath automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface DocumentUserDocumentPullRequestPath {
    user?: string
    document?: string
}
