/**
 * ExploreResource automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {AxiosInstance, AxiosRequestConfig, AxiosResponse} from "axios";
import {ResourceAbstract} from "sdkgen-client"
import {AppModelCollectionQuery} from "./AppModelCollectionQuery";
import {DocumentCollection} from "./DocumentCollection";

export default class ExploreResource extends ResourceAbstract {
    private url: string;


    public constructor(baseUrl: string, httpClient: AxiosInstance) {
        super(baseUrl, httpClient);


        this.url = baseUrl + "/explore";
    }

    /**
     * Returns trending documents
     *
     * @param {AppModelCollectionQuery} query
     * @returns {Promise<AxiosResponse<DocumentCollection>>}
     */
    public async getExplore(query?: AppModelCollectionQuery): Promise<AxiosResponse<DocumentCollection>> {
        let params: AxiosRequestConfig = {
            method: 'GET',
            params: query,
        };

        return this.httpClient.get<DocumentCollection>(this.url, params);
    }

}
