/**
 * Issue automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {User} from "./User";
import {Document} from "./Document";

export interface Issue {
    id?: number
    user?: User
    document?: Document
    status?: number
    title?: string
    updateDate?: string
    insertDate?: string
}

