/**
 * IssueCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Issue} from "./Issue";

export interface IssueCollection extends Collection<Issue> {
}

