/**
 * IssueCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {Issue} from "./Issue";

export interface IssueCollection extends Collection<Issue> {
}

