/**
 * MethodDistribution automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface MethodDistribution {
    get?: number
    post?: number
    put?: number
    delete?: number
    patch?: number
}

