/**
 * PrimitiveTypeDistribution automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface PrimitiveTypeDistribution {
    string?: number
    integer?: number
    number?: number
    boolean?: number
    object?: number
    map?: number
    array?: number
    any?: number
    generic?: number
}

