/**
 * PullRequest automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Document} from "./Document";
import {PullRequestContext} from "./PullRequestContext";
import {User} from "./User";
export interface PullRequest {
    id?: number
    status?: number
    source?: Document
    target?: Document
    context?: PullRequestContext
    user?: User
    title?: string
    updateDate?: string
    insertDate?: string
}
