/**
 * PullRequestCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface PullRequestCreate {
    title?: string
    description?: string
}

