/**
 * PullRequestCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {PullRequest} from "./PullRequest";

export interface PullRequestCollection extends Collection<PullRequest> {
}

