/**
 * PullRequestContext automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface PullRequestContext {
    source?: any
    target?: any
    merged?: any
}
