/**
 * PullRequestCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {PullRequest} from "./PullRequest";
export type PullRequestCollection = Collection<PullRequest>;
