/**
 * Repository automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {User} from "./User";
import {Document} from "./Document";
export interface Repository {
    id?: number
    user?: User
    document?: Document
    generator?: string
    url?: string
    username?: string
    password?: string
    folder?: string
    config?: string
    updateDate?: string
    insertDate?: string
}
