/**
 * RepositoryCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Repository} from "./Repository";
export interface RepositoryCreate extends Repository {
}
