/**
 * ResourceGroup automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface ResourceGroup {
    prefix?: string
    operationCount?: number
}

