/**
 * Statistic automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {ArgumentDistribution} from "./ArgumentDistribution";
import type {MethodDistribution} from "./MethodDistribution";
import type {PrimitiveTypeDistribution} from "./PrimitiveTypeDistribution";
import type {PropertyBucket} from "./PropertyBucket";
import type {ResourceGroup} from "./ResourceGroup";
import type {LargestType} from "./LargestType";
import type {NameCount} from "./NameCount";

export interface Statistic {
    operationCount?: number
    typeCount?: number
    averagePropertiesPerType?: number
    typeReusabilityIndex?: number
    maxPathDepth?: number
    avgParamsPerOperation?: number
    extendedTypeCount?: number
    discriminatorTypeCount?: number
    maxTypeNestingDepth?: number
    argumentDistribution?: ArgumentDistribution
    methodDistribution?: MethodDistribution
    primitiveDistribution?: PrimitiveTypeDistribution
    propertyComplexity?: Array<PropertyBucket>
    topResourceGroups?: Array<ResourceGroup>
    largestTypes?: Array<LargestType>
    mostUsedProperties?: Array<NameCount>
    mostUsedArguments?: Array<NameCount>
}

