/**
 * TagCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Collection} from "./Collection";
import type {Tag} from "./Tag";

export interface TagCollection extends Collection<Tag> {
}

