/**
 * TriggerCreate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Trigger} from "./Trigger";

export interface TriggerCreate extends Trigger {
}

