/**
 * Trigger automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {User} from "./User";
import type {Document} from "./Document";
import type {TriggerConfig} from "./TriggerConfig";

export interface Trigger {
    id?: number
    user?: User
    document?: Document
    type?: string
    config?: TriggerConfig
    updateDate?: string
    insertDate?: string
}

