/**
 * TriggerUpdate automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import type {Trigger} from "./Trigger";

export interface TriggerUpdate extends Trigger {
}

