/**
 * TriggerCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Trigger} from "./Trigger";
export type TriggerCollection = Collection<Trigger>;
