/**
 * Trigger automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {User} from "./User";
import {Document} from "./Document";
import {TriggerConfig} from "./TriggerConfig";
export interface Trigger {
    id?: number
    user?: User
    document?: Document
    type?: string
    config?: TriggerConfig
    updateDate?: string
    insertDate?: string
}
